- name: Add SSH key via Gitea API
  ansible.builtin.uri:
    url: "{{ gitea.api.url }}/user/keys"
    method: POST
    headers:
      Authorization: "token {{ gitea.api.token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      title: "{{ ssh_key_title }}"
      key: "{{ ssh_key_content['content'] | b64decode }}"
    status_code: 201
