[metadata]
name = "emoji"
description = "Search emojis and copy to clipboard"
requirements = ["python", "wl-copy"]

[source]
command = "python -S ~/.config/television/scripts/emoji_source.py"
display = "{split:\\t:1}  {split:\\t:2}"
output = "{split:\\t:1}"
no_sort = true

[keybindings]
enter = "actions:copy"

[actions.copy]
description = "Copy emoji"
command = "printf %s '{split:\\t:1}' | wl-copy"
mode = "execute"
