after-login-command = []
after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles' # Possible values: tiles|accordion
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal =  10
inner.vertical   =  10
outer.left       = [ { monitor."samsung"  = 200 }, 10 ]
outer.bottom     = [ { monitor."samsung"  =  50 }, 10 ]
outer.top        = [ { monitor."samsung"  = 200 }, 10 ]
outer.right      = [ { monitor."samsung"  = 200 }, 10 ]

[mode.main.binding]
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-y = 'layout horizontal vertical'
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'
alt-q = 'workspace Q' # top keyboard row
alt-w = 'workspace W'
alt-e = 'workspace E'
alt-r = 'workspace R'
alt-t = 'workspace T'
alt-y = 'workspace Y'
alt-u = 'workspace U'
alt-i = 'workspace I'
alt-o = 'workspace O'
alt-p = 'workspace P'
alt-m = 'workspace M'
alt-n = 'workspace N'
alt-shift-m = 'mode movenodetoworkspace'
alt-shift-r = 'mode resize'
alt-shift-s = 'mode service'

[mode.movenodetoworkspace.binding]
q = 'mode main'
esc = 'mode main'
alt-q = ['move-node-to-workspace Q', 'mode main']
alt-w = ['move-node-to-workspace W', 'mode main']
alt-e = ['move-node-to-workspace E', 'mode main']
alt-r = ['move-node-to-workspace R', 'mode main']
alt-t = ['move-node-to-workspace T', 'mode main']
alt-y = ['move-node-to-workspace Y', 'mode main']
alt-u = ['move-node-to-workspace U', 'mode main']
alt-i = ['move-node-to-workspace I', 'mode main']
alt-o = ['move-node-to-workspace O', 'mode main']
alt-p = ['move-node-to-workspace P', 'mode main']
alt-m = ['move-node-to-workspace M', 'mode main']
alt-n = ['move-node-to-workspace N', 'mode main']

[mode.resize.binding]
q = 'mode main'
esc = 'mode main'
alt-j = 'resize smart -50'
alt-k = 'resize smart +50'

[mode.service.binding]
q = 'mode main'
esc = 'mode main'
r = ['reload-config', 'mode main']
alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace Y'

# [[on-window-detected]]
# if.app-id = 'company.thebrowser.Browser'
# run = 'move-node-to-workspace U'

[[on-window-detected]]
if.app-id = 'com.vivaldi.Vivaldi'
run = 'move-node-to-workspace U'

[[on-window-detected]]
if.app-id = 'org.mozilla.com.zen.browser'
run = 'move-node-to-workspace U'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace U'

[[on-window-detected]]
if.app-id = 'com.TickTick.task.mac'
run = 'move-node-to-workspace I'

[[on-window-detected]]
if.app-id = 'com.electron.logseq'
run = 'move-node-to-workspace I'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace N'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace N'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace E'

[[on-window-detected]]
if.app-id = 'ru.keepcoder.Telegram'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
run = ['layout floating']

