windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false

windowrule = opacity 0.8, match:class obsidian
windowrule = workspace 3, match:class obsidian

windowrule = float yes, match:class rofi
windowrule = float yes, match:class Bitwarden
windowrule = float yes, match:title ^(Picture in picture)$
windowrule = float yes, match:title ^(.*Twitch.*)$

windowrule = float yes, match:title ^(.*htop-floating.*)$
windowrule = size 900 600, match:title ^(.*htop-floating.*)$
windowrule = center yes, match:class ^(.*htop-floating.*)$

windowrule = float yes, match:class ^(org\.netrs\.ui)
windowrule = float yes, match:class ^(org\.pulseaudio\.pavucontrol)
windowrule = float yes, match:class ^(blueman-manager)
