# https://docs.atuin.sh/main/configuration/config/

search_mode = "fuzzy"
enter_accept = false

sync_address = "https://atuin.local.vgerasimov.dev"
auto_sync = true
sync_frequency = "1h"

[tmux]
enabled = false
width = "80%"
height = "60%"

[ai]
enabled = true
