import = [
  #"~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
  #"~/.config/alacritty/catppuccin-mocha.toml"
  #"~/.config/alacritty/4bit-colors.toml"
  #"~/.config/alacritty/tokyo-night.toml"

  # Collection of Alacritty color schemes
  # https://github.com/alacritty/alacritty-theme
  "~/dotfiles/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[font]
size   = 12
normal = { family = "Hack Nerd Font", style = "Regular" }
bold   = { family = "Hack Nerd Font", style = "Bold"    }
italic = { family = "Hack Nerd Font", style = "Italic"  }

[window]
# It is just not pretty
#opacity = 0.75
#blur = true
padding = { x = 10, y = 10 }
decorations = "Buttonless"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001e"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00015"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00016"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00017"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00018"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00019"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001d"
key = "Q"
mods = "Command"

