[default_session]
# startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "main"

[[session]]
name = "trading"
path = "~/Projects/trading"

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "yy"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "~/.config/sesh/dotfiles.sh"

[[session]]
name = "vim"
path = "~/dotfiles/.config/nvim"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "homelab"
path = "~/Projects/homelab"
startup_command = "~/.config/sesh/homelab.sh"

[[session]]
name = "notes"
path = "~/notes"

[[session]]
name = "keyboard"
path = "~/Projects/my-keeb"
